version: "3.9"
services:
  api:
    build: ./back
    ports:
      - "8080:8080"
    volumes:
      - ./back/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
